version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_LOGGING: true
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - tech-test-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'CLI_JAVA_OPTS=-XX:UseSVE=0'
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=

  filebeat:
    image: elastic/filebeat:8.16.5
    restart: unless-stopped
    user: root
    command: [ "filebeat", "-e", "--strict.perms=false" ]
    volumes:
      - ./logs:/logs
      - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
      - kibana

volumes:
  dbdata:
    driver: local

networks:
  tech-test-network:
    driver: bridge
