version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tech-test-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_LOGGING: true
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - tech-test-network

networks:
  tech-test-network:
    driver: bridge
