version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tech-test-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_LOGGING: true
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - tech-test-network

volumes:
  dbdata:
    driver: local

networks:
  tech-test-network:
    driver: bridge
