name: "tech-test-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false

setup.template.enabled: true
setup.template.name: "tech-test"
setup.template.pattern: "tech-test-*"
setup.template.settings:
  index:
    number_of_shards: 1
    number_of_replicas: 1
  mappings:
    properties:
      metric:
        type: text
        fields:
          keyword:
            type: keyword

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    paths:
      - /logs/*.log
    fields:
      - service: tech-test
    fields_under_root: true
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: 'message'


output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "tech-test"